"""Python 3.12/Pollard 1.6 display oracle and Unicode printable lookup data."""
import hashlib
import json
from pathlib import Path
import sys
import unicodedata

wheel = Path(sys.argv[1]).resolve()
sha = "569fb5f130a82c9be327b8dcbd285e3be063200bd9773ca15c5d6bb62edd627f"
assert hashlib.sha256(wheel.read_bytes()).hexdigest() == sha
assert unicodedata.unidata_version == "15.0.0", "regenerate with the pinned Python 3.12 Unicode oracle"
sys.path.insert(0, str(wheel))
import pollard
from pollard.cli import _label
from pollard.otel import _span_name
from pollard.tree import Node
assert pollard.__version__ == "1.6.0" and str(wheel) in pollard.__file__

ranges = []
for code in range(0x110000):
    if not chr(code).isprintable():
        if ranges and ranges[-1][1] + 1 == code: ranges[-1][1] = code
        else: ranges.append([code, code])
source = "// Generated by tests/generate_display_parity.py; Unicode 15.0.0 / Python 3.12.\n"
source += "const NONPRINTABLE: &[(u32, u32)] = &[\n"
source += "".join(f"    (0x{first:x}, 0x{last:x}),\n" for first, last in ranges)
source += "];\n"
Path(__file__).parent.parent.joinpath("src/python_printable.rs").write_bytes(source.encode())

boundaries = {code for first, last in ranges for code in [first - 1, first, last, last + 1]
              if 0 <= code < 0x110000 and not 0xd800 <= code <= 0xdfff}
values = [None, True, False, 0, -(2**128), 2**128, "", "'", '"', "both '\" quotes\\\n\t\r",
          "café 🦊 e\u0301 \u4e16\u754c", [], {}, [None, True, False, 3, "quote'"],
          {"nested": [None, {"str": "both '\" quotes", "control": "\x00\x7f\u200b"}], "é": True},
          ["".join(chr(code) for code in sorted(boundaries))]]
fixtures = {"provenance": {"wheel_sha256":sha, "unicode_version":unicodedata.unidata_version,
              "unicode_source_sha256":hashlib.sha256(source.encode()).hexdigest()}, "cases":[]}
for value in values:
    for wrapped in [value, [value], {"key'": value}]:
        tool = Node.make(kind="tool_call", parent="a"*64, payload={"tool":wrapped})
        refusal = Node.make(kind="refusal", parent="a"*64, payload={"reason":wrapped})
        fixtures["cases"].append({"value":wrapped, "span_name":_span_name(tool), "label":_label(refusal)})
Path(__file__).with_name("pypi160_display.json").write_text(json.dumps(fixtures, ensure_ascii=False, indent=2)+"\n", encoding="utf-8")
print(f"Generated {len(ranges)} Unicode ranges and {len(fixtures['cases'])} display cases")
